/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AURELIA E-Commerce API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface RegisterInput {
  name: string;
  email: string;
  password: string;
}

export interface LoginInput {
  email: string;
  password: string;
}

export type UserRole = typeof UserRole[keyof typeof UserRole];


export const UserRole = {
  user: 'user',
  admin: 'admin',
} as const;

export interface User {
  id: string;
  name: string;
  email: string;
  role: UserRole;
  createdAt?: string;
}

export interface AuthResponse {
  token: string;
  user: User;
}

export interface Product {
  id: string;
  name: string;
  description: string;
  price: number;
  /** @nullable */
  comparePrice?: number | null;
  category: string;
  stock: number;
  images: string[];
  rating?: number;
  reviewCount?: number;
  featured?: boolean;
  tags?: string[];
  createdAt?: string;
}

export interface ProductInput {
  name: string;
  description: string;
  price: number;
  /** @nullable */
  comparePrice?: number | null;
  category: string;
  stock: number;
  images?: string[];
  featured?: boolean;
  tags?: string[];
}

export interface ProductListResponse {
  products: Product[];
  total: number;
  page: number;
  pages: number;
}

export interface Category {
  name: string;
  count: number;
}

export interface CartItem {
  product: Product;
  quantity: number;
  price: number;
}

export interface Cart {
  items: CartItem[];
  total: number;
  itemCount?: number;
}

export interface CartItemInput {
  productId: string;
  quantity: number;
}

export interface CartItemUpdate {
  quantity: number;
}

export interface ShippingAddress {
  fullName: string;
  address: string;
  city: string;
  postalCode: string;
  country: string;
  /** @nullable */
  phone?: string | null;
}

export interface OrderItem {
  product: string;
  name: string;
  quantity: number;
  price: number;
  image: string;
}

export type OrderStatus = typeof OrderStatus[keyof typeof OrderStatus];


export const OrderStatus = {
  pending: 'pending',
  processing: 'processing',
  shipped: 'shipped',
  delivered: 'delivered',
  cancelled: 'cancelled',
} as const;

export interface Order {
  id: string;
  user: string;
  items: OrderItem[];
  shippingAddress: ShippingAddress;
  status: OrderStatus;
  total: number;
  paymentMethod?: string;
  isPaid?: boolean;
  /** @nullable */
  paidAt?: string | null;
  createdAt: string;
}

export interface OrderInput {
  shippingAddress: ShippingAddress;
  paymentMethod: string;
}

export type OrderStatusUpdateStatus = typeof OrderStatusUpdateStatus[keyof typeof OrderStatusUpdateStatus];


export const OrderStatusUpdateStatus = {
  pending: 'pending',
  processing: 'processing',
  shipped: 'shipped',
  delivered: 'delivered',
  cancelled: 'cancelled',
} as const;

export interface OrderStatusUpdate {
  status: OrderStatusUpdateStatus;
}

export interface StatusCount {
  status: string;
  count: number;
}

export interface MonthRevenue {
  month: string;
  revenue: number;
}

export interface DashboardStats {
  totalRevenue: number;
  totalOrders: number;
  totalProducts: number;
  totalUsers: number;
  recentOrders: Order[];
  topProducts: Product[];
  ordersByStatus: StatusCount[];
  revenueByMonth: MonthRevenue[];
}

export type ListProductsParams = {
q?: string;
category?: string;
minPrice?: number;
maxPrice?: number;
sort?: ListProductsSort;
page?: number;
limit?: number;
};

export type ListProductsSort = typeof ListProductsSort[keyof typeof ListProductsSort];


export const ListProductsSort = {
  newest: 'newest',
  price_asc: 'price_asc',
  price_desc: 'price_desc',
  rating: 'rating',
} as const;

