/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AURELIA E-Commerce API
 * OpenAPI spec version: 0.1.0
 */
import type { MonthRevenue } from './monthRevenue';
import type { Order } from './order';
import type { Product } from './product';
import type { StatusCount } from './statusCount';

export interface DashboardStats {
  totalRevenue: number;
  totalOrders: number;
  totalProducts: number;
  totalUsers: number;
  recentOrders: Order[];
  topProducts: Product[];
  ordersByStatus: StatusCount[];
  revenueByMonth: MonthRevenue[];
}
