/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AURELIA E-Commerce API
 * OpenAPI spec version: 0.1.0
 */
import type { ListProductsSort } from './listProductsSort';

export type ListProductsParams = {
q?: string;
category?: string;
minPrice?: number;
maxPrice?: number;
sort?: ListProductsSort;
page?: number;
limit?: number;
};
