/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AURELIA E-Commerce API
 * OpenAPI spec version: 0.1.0
 */
import type { OrderItem } from './orderItem';
import type { OrderStatus } from './orderStatus';
import type { ShippingAddress } from './shippingAddress';

export interface Order {
  id: string;
  user: string;
  items: OrderItem[];
  shippingAddress: ShippingAddress;
  status: OrderStatus;
  total: number;
  paymentMethod?: string;
  isPaid?: boolean;
  /** @nullable */
  paidAt?: string | null;
  createdAt: string;
}
