/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AURELIA E-Commerce API
 * OpenAPI spec version: 0.1.0
 */

export interface Product {
  id: string;
  name: string;
  description: string;
  price: number;
  /** @nullable */
  comparePrice?: number | null;
  category: string;
  stock: number;
  images: string[];
  rating?: number;
  reviewCount?: number;
  featured?: boolean;
  tags?: string[];
  createdAt?: string;
}
